import { IMenuProvider, MenuItem } from "./index";

export class MenuFakeProvider implements IMenuProvider {

    public getAllItems(): Promise<MenuItem[]> {
        return new Promise<MenuItem[]>((resolve, reject) => {

            let result: MenuItem[] = [
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Animal Health & Welfare", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Customer Service", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Farmer Schemes & Payments", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Farming Sectors", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Food Industry Development, Trade, Markets and the Economy", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Food Safety, Public Health & Consumer Issues", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Forestry", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Research", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Rural Environment", url: "url1" },
                {id: 1, category: "Department of Agriculture, Food and the Marine", name: "Seafood", url: "url1" },

                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Built Heritage, Architectural Policy & Strategic Infrastructure", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "National Monuments Service", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "National Parks & Wildlife Service", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Moore Street Consultative Group", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Publications", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Legislation", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Heritage Links", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "The Irish Language", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "The Gaeltacht", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "20-Year Strategy for the Irish Language", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Islands", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Recruitment", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Publications", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Legislation", url: "url1" },
                {id: 2, category: "Department of Arts, Heritage, Regional, Rural and Gaeltacht Affairs", name: "Gaeltacht Links", url: "url1" },


                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Innovation, Research & Development", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Trade & Investment", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Supports for SMEs", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Business & Sectoral Initiatives", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Workplace & Skills", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "EU & Internal Market", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Company & Corporate Law", url: "url1" },
                {id: 3, category: "Department of Business, Enterprise and Innovation", name: "Consumer & Competition", url: "url1" },
               



                {id: 4, category: "Department of Children and Youth Affairs", name: "Childcare", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Tusla", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Children In Care", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Participation", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Play, Recreation & Culture", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Children and Young People's Participation Hub", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Children First", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Child Welfare and Protection", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Adoption", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Irish Youth Justice Service", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Youth Affairs", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Area Based Childhood (ABC) Programme", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Mother and Baby Homes Investigation", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Children and Young People's Services Committees (CYPSC)", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Reform of Guardian ad litem Arrangements", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Quality and Capacity Building Initiative", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Better Outcomes, Brighter Futures", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Legislation", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "International Framework", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Growing Up in Ireland", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Research", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "National Research and Data Strategy", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Financial Information", url: "url1" },
                {id: 4, category: "Department of Children and Youth Affairs", name: "Freedom of Information", url: "url1" },

                {id: 5, category: "Department of Communications, Climate Action & Environment", name: "Communications", url: "url1" },
                {id: 5, category: "Department of Communications, Climate Action & Environment", name: "Climate Action", url: "url1" },
                {id: 5, category: "Department of Communications, Climate Action & Environment", name: "Environment", url: "url1" },
                {id: 5, category: "Department of Communications, Climate Action & Environment", name: "Energy", url: "url1" },
                {id: 5, category: "Department of Communications, Climate Action & Environment", name: "Natural Resources", url: "url1" },
                {id: 5, category: "Department of Communications, Climate Action & Environment", name: "Compliance", url: "url1" },

                
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Jobseekers", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Employers and Employment", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Children and Families", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Disability and Illness", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Retired and Older People", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Bereavement", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Other Supports", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Supplementary Welfare Allowance", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Moving to or from Ireland", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Public Service Identity", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Redundancy and Insolvency", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Translations & Interpretive Services", url: "url1" },
                {id: 5, category: "Department of Employment Affairs and Social Protection (DEASP)", name: "Freedom of Information", url: "url1" },

                {id: 5, category: "Department of Education and Skills", name: "School Holidays", url: "url1" },
                {id: 5, category: "Department of Education and Skills", name: "Child Protection", url: "url1" },
                {id: 5, category: "Department of Education and Skills", name: "School Enrolment", url: "url1" },
                {id: 5, category: "Department of Education and Skills", name: "State Examinations", url: "url1" },
                {id: 5, category: "Department of Education and Skills", name: "Data on Individual Schools", url: "url1" },
                {id: 5, category: "Department of Education and Skills", name: "Inspection Reports and Publications", url: "url1" },
                
                {id: 5, category: "Department of Finance", name: "Economic", url: "url1" },
                {id: 5, category: "Department of Finance", name: "Public Finances", url: "url1" },
                {id: 5, category: "Department of Finance", name: "Tax", url: "url1" },
                {id: 5, category: "Department of Finance", name: "The Budget", url: "url1" },
                {id: 5, category: "Department of Finance", name: "Banking", url: "url1" },
                {id: 5, category: "Department of Finance", name: "Financial Services", url: "url1" },
                {id: 5, category: "Department of Finance", name: "Insurance", url: "url1" },
                {id: 5, category: "Department of Finance", name: "Shareholding & Financial Advisory", url: "url1" },
                {id: 5, category: "Department of Finance", name: "International Financial Services", url: "url1" },
                {id: 5, category: "Department of Finance", name: "EU & International", url: "url1" },
                {id: 5, category: "Department of Finance", name: "International Institutions", url: "url1" },

                {id: 5, category: "Department of Foreign Affairs and Trade", name: "Passports and Citizenship", url: "url1" },
                {id: 5, category: "Department of Foreign Affairs and Trade", name: "Travel", url: "url1" },
                {id: 5, category: "Department of Foreign Affairs and Trade", name: "Embassies", url: "url1" },
                {id: 5, category: "Department of Foreign Affairs and Trade", name: "News and Media", url: "url1" },

                
                {id: 5, category: "Department of Housing, Planning, Community and Local Government", name: "Housing", url: "url1" },
                {id: 5, category: "Department of Housing, Planning, Community and Local Government", name: "Planning", url: "url1" },
                {id: 5, category: "Department of Housing, Planning, Community and Local Government", name: "Local Government", url: "url1" },
                {id: 5, category: "Department of Housing, Planning, Community and Local Government", name: "Met Éireann", url: "url1" },
                {id: 5, category: "Department of Housing, Planning, Community and Local Government", name: "Local Government Audit Service", url: "url1" },
                {id: 5, category: "Department of Housing, Planning, Community and Local Government", name: "Corporate", url: "url1" },

                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Justice and Equality", name: "Workplace & Skills", url: "url1" },
                
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Public Expenditure and Reform", name: "Workplace & Skills", url: "url1" },

                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of the Taoiseach", name: "Workplace & Skills", url: "url1" },

                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" },
                {id: 5, category: "Department of Transport, Tourism and Sport", name: "Workplace & Skills", url: "url1" }

            ];

            resolve(result);
        });
    }
}